# Generated by Django 2.1 on 2019-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_tag',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='个新签名'),
        ),
    ]
