# Generated by Django 2.1 on 2019-06-11 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(max_length=500, verbose_name='留言内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/message/', verbose_name='图片')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='message.Message', verbose_name='被回复留言的id')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages1', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages2', to=settings.AUTH_USER_MODEL, verbose_name='被评论者')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'message',
            },
        ),
    ]
