# Generated by Django 2.1 on 2019-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='被回复留言的id'),
        ),
    ]
