# Generated by Django 2.1 on 2019-06-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_to_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_id',
            new_name='to_msg_id',
        ),
    ]
