# Generated by Django 2.1 on 2019-06-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190605_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_msg_id',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='message.Message', verbose_name='被回复留言的id'),
        ),
        migrations.AddField(
            model_name='message',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='message.Message', verbose_name='被回复留言的id'),
        ),
    ]
