# Generated by Django 2.1 on 2019-05-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190518_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='aixin',
            field=models.IntegerField(default=0),
        ),
    ]
