# Generated by Django 2.1 on 2019-05-23 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_topic_aixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.IntegerField(choices=[(1, '美词佳句'), (2, '经典说说'), (3, '搞笑说说'), (4, '爱情说说'), (5, '伤感说说')], default=1, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='blog_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='index.BlogType', verbose_name='博客类型'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='发表用户'),
        ),
    ]
