# Generated by Django 2.1 on 2019-05-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190528_1002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reply',
            table='reply',
        ),
    ]
