# Generated by Django 2.1 on 2019-06-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190614_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply1s', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
    ]
